### ISSUE TITLE
add "scale" support to BigDecimal

### ISSUE THREAD

**Issue by skolson** [ionspin/kotlin-multiplatform-bignum#122]
When using BigDecimal for currency calculations, having the functionality of "scale" in java's BigDecimal is very useful, as it is in a number of other use cases.  I don't think the equivalent of "scale" is available in the current implementation.

A general list of changes required to BigDecimal class:

- scale:Int added as a val argument to constructor(s). Will be verified to be between 0 and precision, Will verify not using infinite precision DecimalMode if scale specified
- fun scale(newScale:Int, roundingMode:RoundingMode = this.decimalMode.roundingMode):BigDecimal 
   will return a new BigDecimal with new scale and specified RoundingMode, using existing fun roundToDigitPositionAfterDecimalPoint
- **Bigger change** - all arithmetic operations would have to be scale-aware. If no scale specified (default), then no change in function.  If scale is specified, use roundToDigitPositionAfterDecimalPoint(scale, decimalMode.roundingMode

Will of course require a set of unit tests testing all of the operations when using scale. Existing unit tests should be fine checking behavior when no scale is specified, as existing functionality shouldn't change.

"scale" can be held inDecimalMode, or in BigDecimal, whatever seems cleanest.

Since I want this, I volunteer to do the changes and crank up a pull request if this sounds like a good idea :-)

**Comment by skolson** [comment]
Thanks!  Will start work tomorrow.

**Comment by skolson** [comment]
My first approach was to add scale as a third constructor are to DecimalMode. Currently signature looks like this:
```
data class DecimalMode(val decimalPrecision: Long = 0,
                       val roundingMode: RoundingMode = RoundingMode.NONE,
                       val scale:Long = -1
)
```
I've tried this with scale like it is, and with val scale:Long? = null. In both cases I can build unit tests and debug them fine, but wither way if I run a gradle build task, it fails in this JS task with this error info:
```
> Task :bignum:compileTestDevelopmentExecutableKotlinJs FAILED
w: ATTENTION!
This build uses unsafe internal compiler arguments:

-XXLanguage:+InlineClasses

This mode is not recommended for production use,
as no stability/compatibility guarantees are given on
compiler or generated code. Use it at your own risk!

e: java.lang.AssertionError: Unbound symbols at the end of linker
Unbound public symbol for public com.ionspin.kotlin.bignum.decimal/DecimalMode.<init>|-5448850544649000342[0] public com.ionspin.kotlin.bignum.decimal/DecimalMode.<init>|-5448850544649000342[0]
	at org.jetbrains.kotlin.ir.util.SymbolTableKt.noUnboundLeft(SymbolTable.kt:962)
	at org.jetbrains.kotlin.ir.backend.js.CompilerKt.compile(compiler.kt:73)
	at org.jetbrains.kotlin.ir.backend.js.CompilerKt.compile$default(compiler.kt:48)
	at org.jetbrains.kotlin.cli.js.K2JsIrCompiler.doExecute(K2JsIrCompiler.kt:221)
	at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.java:181)
	at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.java:74)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:86)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:44)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:98)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1549)
	at sun.reflect.GeneratedMethodAccessor103.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)


FAILURE: Build failed with an exception.
```
Do you know what I did to cause this?

**Comment by ionspin** [comment]
Looks like a bug in Kotlin JS compiler, I've hit a few here and there, mostly it's possible to work around them. Can you share your branch, so I can try to reproduce the bug?

**Comment by ionspin** [comment]
Btw, I tried just making this change:
```data class DecimalMode(val decimalPrecision: Long = 0,
                       val roundingMode: RoundingMode = RoundingMode.NONE,
                       val scale:Long = -1
)```
And build passed without errors (expect spotless). You could also try cleaning the project with `./gradlew clean`, it's a shot in the dark, but sometimes it helps with JS.

**Comment by skolson** [comment]
I don't know what I did, but the above problem disappeared, I have a first draft of scale support working, and it has passed spotless, done a full build, and fails one JS test:
```
specificDivide[js, browser, PhantomJS2.1.1, Windows8.0.0]
Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```
How do I chase this down?
Either way on the JS test, what I have should be good enough for review and polishing. Is this a good time for me to create a pull request so you can review stuff?  I'm also wide open to any additional scale-related unit tests you can think of. Almost all of the new ones I did are related to currency usage, so I'm open to suggestions on others.  I looked in the openjdk source and was surprised that I couldn't find unit tests specifically targeting scale functionality in BigDecimal. So I couldn't snarf theirs :-)

**Comment by ionspin** [comment]
Great! I'll take a look at the commit tomorrow. For the failing JS test, you can just annotate it with @Ignore for now (but don't commit that annotation :) ), it passes reliably on Travis, so it's probably just that it takes longer on your machine.
